app/build.gradle.kts, build.gradle.kts
This requires a valid google-services.json. This is provided as a GitHub secret for release builds, but is a mock one for all other builds.
=> Enable Firebase crashylitics

.github/workflows/run-tests.yaml
Failing tests had little info to help debug the error. This change means that the logcat for failed tests is uploaded as an artifact.
=> Upload logcat on instrumentation test failure

app/build.gradle.kts, app/src/androidTest/java/org/scottishtecharmy/soundscape/GpxTest.kt, app/src/main/assets/gpx/handcrafted.gpx, app/src/main/assets/gpx/rideWithGps.gpx, app/src/main/assets/gpx/soundscape.gpx, app/src/main/java/org/scottishtecharmy/soundscape/database/local/dao/RoutesDao.kt, app/src/main/java/org/scottishtecharmy/soundscape/database/local/model/RouteData.kt, app/src/main/java/org/scottishtecharmy/soundscape/database/repository/RoutesRepository.kt, app/src/main/java/org/scottishtecharmy/soundscape/utils/GpxUtils.kt, build.gradle.kts
These commits add geospatial database support and extend the scope of the tests to support multiple routes in the database at the same time.
=> Further GpxTest work

app/src/main/java/org/scottishtecharmy/soundscape/database/local/RealmConfiguration.kt
Adding RouteData was causing the database opening to fail - possibly because there was already a database file and the schema differed. Once we start using RouteData come up with a migration plan or use a separate database.
=> Remove RouteData from RealConfiguration

app/src/androidTest/java/org/scottishtecharmy/soundscape/AudioEngineTest.kt, app/src/main/cpp/AudioEngine.cpp, app/src/main/cpp/AudioEngine.h, app/src/main/cpp/BeaconDescriptor.h, app/src/main/java/org/scottishtecharmy/soundscape/audio/AudioEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/audio/NativeAudioEngine.kt
getListOfBeaconTypes returns a list of the names of the available beacons within the AudioEngine. This is to allow the UI to interrogate the AudioEngine rather than having two separate lists of beacon types. In addition, I didn't understand enough about Instrumentation tests when I wrote the AudioEngine code. Now that I do, I've added a belated set of initial tests.
=> Add getListOfBeaconTypes to AudioEngine and instrumentation test for it

app/src/androidTest/java/org/scottishtecharmy/soundscape/AudioEngineTest.kt, app/src/main/cpp/AudioEngine.cpp, app/src/main/java/org/scottishtecharmy/soundscape/audio/AudioEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/audio/NativeAudioEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt
AudioEngine.setBeaconType takes a String which is the name of the Beacon type to use. The test loops tests every Beacon type that AudioEngine reports, rotating the listener so that the sound for each of the orientation angles is played. This is done fairly quickly so as not to make the test over long.
Some other mistakes were also fixed - com_scottishtecharmy_soundscape were replaced with org_scottishtecharmy_soundscape.
=> Implement AudioEngine setBeaconType and add test for it

.github/workflows/jekyll-gh-pages.yml, app/src/screenshotTest/kotlin/org/scottishtecharmy/soundscape/PreviewTest.kt, docs/README.md, docs/image.sh, docs/screenshots.md
We could include the report from the preview screenshot validation test, but that requires validating against reference images which we don't have yet. Instead, we build the reference images and use some very basic HTML to display all of the screenshots for each Test. The full resolution test can be saved from the link and so this should give us automatic screenshots of each screen in all locale and a couple of screen sizes.
=> Try including screenshots in documentation compilation

app/build.gradle.kts, app/src/main/java/org/scottishtecharmy/soundscape/components/LanguageSelectionBox.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/onboarding/AudioBeacons.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/onboarding/Language.kt, gradle/libs.versions.toml
Firebase was reporting a test issue:
Your app uses 1 non-SDK interfaces, which are incompatible with Android P+.
Ljava/lang/invoke/MethodHandles$Lookup;-><init>(Ljava/lang/Class;I)V
It turns out that initializing ViewModel data inside an init function is a bad idea - see
https://www.droidcon.com/2024/03/22/mastering-android-viewmodels-essential-dos-and-donts-part-1-%f0%9f%9b%a0%ef%b8%8f/
This change removes the init from AudioBeaconsViewModel and instead uses a flow to initialize the list of beacon types. That initialization will now happen when the UI code calls into the ViewModel with collectAsStateWithLifecycle instead of when theAudioBeaconsViewModel was created.
The LanguageViewModel has been changed in the same way. The list of supported languages is now in a flow and is only …
=> Deliver onboarding screens' ViewModel data as flows

.github/workflows/build-app.yaml, .github/workflows/jekyll-gh-pages.yml, .github/workflows/nightly.yaml, .github/workflows/run-tests.yaml
Putting the screenshots in the docs increased the overhead of docs compilation by a factor of 10 and the result wasn't that readable. This change removes that and instead we build screenshots during all of the other actions. Release and nightly builds both upload them as artifacts which should make them easily accessible for developeres.
=> Remove screenshots from docs but build them everywhere else

app/build.gradle.kts, app/src/main/res/values-v31/splash.xml, gradle/libs.versions.toml
minSdk can drop to 29 because it turns out that the splash screen is supported on that release too, just not as well. AndroidStudio has been complaining about the targetSdk not being the latest, so bump that up at the same time. In doing so move the dependencies to using libs.versions.toml which is the current way to handle package versions.
=> Reduce minSdk version, increase targetSdk version and increase use of libs.versions.toml

app/src/main/java/org/scottishtecharmy/soundscape/components/LanguageSelectionBox.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/onboarding/AudioBeacons.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/onboarding/Hearing.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/onboarding/Language.kt, app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/AudioBeaconsViewModel.kt, app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/HearingViewModel.kt, app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/LanguageViewModel.kt
Android Studio does this with a few clicks via Refactor (F6). Moved them next to the PermissionsViewModel.
=> Move onboarding screen ViewModels into their own files

.github/workflows/build-app.yaml, .github/workflows/nightly.yaml, app/build.gradle.kts, app/src/main/java/org/scottishtecharmy/soundscape/MainActivity.kt, app/src/main/java/org/scottishtecharmy/soundscape/SoundscapeServiceConnection.kt, app/src/main/java/org/scottishtecharmy/soundscape/di/HiltModule.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/Home.kt, app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt, app/src/main/java/org/scottishtecharmy/soundscape/utils/TileUtils.kt, app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/HomeViewModel.kt, app/src/test/java/org/scottishtecharmy/soundscape/TileUtilsTest.kt, docs/actions.md, gradle/libs.versions.toml
This code is the initial integration of the MapCompose open street map UI. The soundscape service connection has been moved out into a separate class and then a MapCompose based UI has been added to the Home screen. The service now uses lastLocation to give a much quicker 'lock' on the current position.
The local map is displayed with a marker displaying the current location. The marker is moved whenever the Soundscape service updates the device location. The map can be zoomed in/out and repositioned independently of the marker location.
The map centers on the current location when the location is first updated. The heading is constantly updated so that the location icon rotates to point in the direcion of the phone.
A long press on the map will create an audio beacon at that location. A …
=> Initial integration of MapCompose map

app/src/main/res/values-v30/splash.xml
Having dropped the SDK level down the splash screen resulted in a crash on API 30 because it didn't inherit from Theme.AppCompat.
=> Fix API 30 splash screen to stop crash

app/build.gradle.kts, app/src/main/java/org/scottishtecharmy/soundscape/screens/Home.kt, app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/HomeViewModel.kt, gradle/libs.versions.toml
Upgrading MapLibre removed all of the outdated MapBox naming so now it's all MapLibre which makes more sense.
Almost all of the warnings in libs.versions.toml were resolved which included:
* Upgrading libraries
* Removing duplicate declarations
* Removing declarations of two different versions of a library (okHttp)
The only remaining out of date library is Realm. If we bump that to 2.x then it doesn't compile (known issues it seems). Otherwise, everything seems to be working the same as before.
=> Upgrade libraries including maplibre

app/src/main/java/org/scottishtecharmy/soundscape/MainActivity.kt, app/src/main/java/org/scottishtecharmy/soundscape/SoundscapeServiceConnection.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/Home.kt, app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt, app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/HomeViewModel.kt
The iOS app had a 'sleep' button in the top right and this change moves towards that model. Clicking on the button toggles the running of the foreground service. When the service isn't running, there's no location/heading update and no text to speech. The icon showing the current location on the map is removed, and then when the service is restarted it reappears and the map is recentered.
Not sure what iOS does in this case, need to compare.
=> Replace button that stops service and exits with sleep toggle

app/src/main/java/org/scottishtecharmy/soundscape/MainActivity.kt
A stray checkAndRequestNotificationPermissions was left in that resulted in the Soundscape service being started twice. That didn't have too much impact except when running teleport where it resulted in the orientation listener being registered twice. Removing the call resolves the issue.
=> Remove double service start

app/src/main/cpp/AudioBeaconBuffer.cpp, app/src/main/cpp/AudioBeaconBuffer.h, app/src/main/cpp/AudioEngine.cpp, app/src/main/cpp/AudioEngine.h, app/src/main/java/org/scottishtecharmy/soundscape/audio/AudioEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/audio/NativeAudioEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt
For the service/app this just means that there's now an `AudioEngine` function which can be called named `clearTextToSpeechQueue()`. I've added calls to that at the start of `aheadOfMe`, `myLocation` and `whatsAroundMe` and those now interrupt each other correctly.
=> Add the ability to clear the text to speech queued audio

docs/actions.md
Because of the way they're handled internally GitHub secrets need to all be on a single line - that's for both JSON and base64. Update the instructions on how to do this.
=> Update actions instructions to remind about removing linebreaks

app/src/main/java/org/scottishtecharmy/soundscape/screens/onboarding/Hearing.kt, app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/HearingViewModel.kt
Now that we can clear the speech queue, call it in the Hearing screen before it exits and before it plays audio. This means that the Listen button can now be hit multiple times to immediately hear the speech.
=> Add clearing of speech queue to stop text when leaving Hearing screen

.github/workflows/jekyll-gh-pages.yml, app/build.gradle.kts, build.gradle.kts, docs/README.md, gradle/libs.versions.toml
This enables dokka markdown generation and includes the output in our GitHub pages site. I've included the mermaid plugin which means that mermaid can be included in comments in the code. Dokka is generated from code containing Kdoc syntax comments, see
https://kotlinlang.org/docs/kotlin-doc.html#kdoc-syntax
=> Add dokka support for auto-generation of code documentation

app/src/main/AndroidManifest.xml, app/src/main/java/org/scottishtecharmy/soundscape/MainActivity.kt, app/src/main/java/org/scottishtecharmy/soundscape/SoundscapeIntents.kt, app/src/main/java/org/scottishtecharmy/soundscape/database/local/RealmConfiguration.kt, app/src/main/java/org/scottishtecharmy/soundscape/database/local/dao/RoutesDao.kt, app/src/main/java/org/scottishtecharmy/soundscape/database/repository/RoutesRepository.kt, app/src/main/java/org/scottishtecharmy/soundscape/services/RoutePlayer.kt, app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt
This is for some very initial testing and development work. If the user selects "Open with Soundscape" on a GPX file from the Android File app then the GPX will be parsed and an inMemory (temporary) database will be created. There's then a new RoutePlayer class which is created to playback the first route that can be found in that database. There's some speech describing when the marker changes and the map reflects the location of the current beacon (marker in the Route).
If the app is launched in any other way, it will work as before with no route available or played back.
=> Initial Route import and playback

app/src/main/java/org/scottishtecharmy/soundscape/SoundscapeIntents.kt, app/src/main/java/org/scottishtecharmy/soundscape/SoundscapeServiceConnection.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/HomeScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/Home.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/locationDetails/LocationDetailsScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt, app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/HomeViewModel.kt, app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/LocationDetailsViewModel.kt
The long term aim is to implement Street Preview mode #147, but in the meantime it's very useful to be able to teleport to a location to test the speech callouts. There are two way to do this:
1. Via `soundscape:` URIs e.g.[`soundscape:55.9517303,-3.2005471`](soundscape:55.9517303,-3.2005471). These open the app in StreetPreview mode at the location provided. This can be provided via Android Studio with Launch Flags e.g. `-d geo:55.8546671,-4.2372673`
2. Clicking the Street Preview button on the LocationDetails screen. That screen can be entered via `geo:` URIs, or sharing a location with Soundscape from Google Maps.
To exit StreetPreview and return to using the device actual location there's a small icon in the top right to click on. When not in StreetPreview mode it is blank.
This UI is …
=> Teleporting changes to aid Geo development

app/src/main/java/org/scottishtecharmy/soundscape/MainActivity.kt, app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/LocationDetailsViewModel.kt
When an intent is used to launch the app that puts it in the LocationDetails screen it should only navigate there when the app first starts. Prior to this change it was also opening that screen whenever the screen is rotated.
There are two changes:
1. Only parse the Intent the first time the service connection is bound, and not subsequent times.
2. Reset the `Navigator` destination to "" once the LocationDetail screen has been displayed and then check for that after a rotate.
=> Don't return to LocationDetails screen on rotate

app/build.gradle.kts, app/src/androidTest/java/org/scottishtecharmy/soundscape/PhotonSearchTest.kt, app/src/main/java/org/scottishtecharmy/soundscape/geojsonparser/geojson/LngLatAlt.kt, app/src/main/java/org/scottishtecharmy/soundscape/network/SearchProvider.kt, gradle/libs.versions.toml
This commit adds a PhotonSearchProvider which can be used to retrieve search results from a komoot photon server. The test shows a simple use case for it. The retrofit API uses Moshi to parse the JSON inline via the MoshiConverterFactory.
=> Initial proof of concept for using Photon search API

app/src/main/java/org/scottishtecharmy/soundscape/MainActivity.kt, app/src/main/java/org/scottishtecharmy/soundscape/SoundscapeServiceConnection.kt, app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt
Leak Canary found a memory leak in the LocalBinder class within the Soundscape service. The implementation was straight from the Android docs, but I guess it's not so common to disconnect from a service when the app isn't shutting down too?
The main fix is to move the LocalBinder class out and add to it a reset() function which removes the reference to the SoundscapeService. When the service is destroyed it calls reset() on the binder and then the garbage collection can continue unhindered.
=> Fix memory leak when stopping Soundscape service

.github/workflows/nightly.yaml
Now that the Robo test is running for the full length of the timeout bump the duration up to 30 seconds.
=> Nightly build Robo test was limited to 5 minutes, bump it up

app/src/main/java/org/scottishtecharmy/soundscape/MainActivity.kt, app/src/main/java/org/scottishtecharmy/soundscape/audio/NativeAudioEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/HomeScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/settings/Settings.kt, app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt, app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/SettingsViewModel.kt
The main aim of this change was to add a list of supported TextToSpeech voices and control of the rate of the speech. To do this, the Settings screen needed some work:
1. It didn't scroll when there were too many settings to fit on screen
2. It didn't deal with the delay in the TextToSpeech engine initialization
The change fixes both of these. The second is done with a flow from the audio engine to indicate when the TextToSpeech engine has been configured. When that's received the Settings screen will recompose with the updated values.
The main issue with the voice names is that their poor! There doesn't seem to be any way to get a description of the Voice from the API, so we're left with their names which are ugly to read. There are various online threads which suggest just mapping these …
=> Update settings with some more audio control and refactor

app/src/main/java/org/scottishtecharmy/soundscape/screens/onboarding/language/LanguageScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/onboarding/language/LanguageViewModel.kt
Without this change the UI stays in English during onboarding, though the language for the speech engine is updated. This does result in the black UI flash returning when a new language is selected, but perhaps that's unavoidable?
=> Update application locale when language is selected

app/src/main/java/org/scottishtecharmy/soundscape/audio/AudioEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/audio/NativeAudioEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/di/HiltModule.kt, app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/SettingsViewModel.kt
The main aim of this change is to update the audio engine whenever any of the audio settings are changed. This is done by listening to changes on the SharedPreferences from within the NativeAudioEngine. As well as updating the audio engine, changes to the speech settings also trigger some speech so that it's easy to fiddle with settings and hear their results. This behaviour is disabled for AudioEngine created by Hilt injection as those are running during onboarding when not all of the preferences have been configured.
Another complication is that prior to this change the SettingsViewModel was creating its own audio engine just to get the possible configuration options. This has been changed so that now it connects to the Soundscape service and uses its audio engine.
=> Update audio engine immediately if any settings change

app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/SettingsViewModel.kt
I installed the Vocalizer TTS app which gives me access to a much wider range of voices. They sound better than Google, are well named, and seem to do a better job with Street vs. Saint abbreviations. However, the locale for the voice I chose was "eng" rather than than the "en" which was in our locale and so the voice was ignored. If no voices are found when checking the list from the TTS engine this change means that it's re-checked this time without matching on the locale language.
=> If no TTS voices are found allow mis-matched locales

app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GeoEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/network/TileClient.kt, app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt, app/src/main/java/org/scottishtecharmy/soundscape/utils/CompassDirections.kt
There's nothing clever going on here, mostly just moving functions around. The only other changes are:
1. The locale configuration is created and held in the GeoEngine to save re-initializing it each time it's required,
2. All functions that require the application context are made within the start() function so that it's only required in that one place.
3. The myLocation, whatsAroundMe and aheadOfMe functions now all return lists of Strings (or PositionedStrings) so that the text can be used in the UI and not just the speech.
=> Move geo functions out of SoundscapeService and into their own class

app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/HomeContent.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/MapContainerLibre.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/locationDetails/LocationDetailsScreen.kt
The map on the main Home screen should always be centered on the phone location, but for other maps it's useful to be able to scroll away from the current location. This adds that control and enables it within the LocationDetailsScreen.
=> Add option of scrolling map in MapContainerLibre

app/src/main/java/org/scottishtecharmy/soundscape/audio/NativeAudioEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GeoEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/onboarding/language/LanguageScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/utils/Locale.kt, app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/SettingsViewModel.kt
There were several places where it was assumed that there was a valid application Locale. This commit replaces those with a call to a utility function which returns the application Locale if it's valid or the default system one if it's not.
=> Use system Locale when an application Locale isn't set

app/src/main/java/org/scottishtecharmy/soundscape/screens/onboarding/hearing/HearingScreen.kt
See issue #201 for discussion on this. Some speech engines read out full stops as 'dot' if there's not a space following them. This avoids it in this one situation.
=> Add space after full stop to add speech engine

app/src/main/java/org/scottishtecharmy/soundscape/MainActivity.kt, app/src/main/java/org/scottishtecharmy/soundscape/SoundscapeServiceConnection.kt, app/src/main/java/org/scottishtecharmy/soundscape/dto/BoundingBox.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GeoEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/locationprovider/LocationProvider.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/HomeScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/Home.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/HomeContent.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/MapContainerLibre.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/locationDetails/LocationDetailsScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/settings/Settings.kt, app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt, app/src/main/java/org/scottishtecharmy/soundscape/utils/GeoUtils.kt, app/src/main/java/org/scottishtecharmy/soundscape/utils/TileGridUtils.kt, app/src/main/java/org/scottishtecharmy/soundscape/utils/TileUtils.kt, app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/HomeViewModel.kt, app/src/test/java/org/scottishtecharmy/soundscape/TileUtilsTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/VisuallyCheckOutput.kt
This commit consists of multiple overlapping changes all with the same
aim which is to add an extra layer of abstraction to the tile grid so
that we can cope with different sized tiles for our audio UI.
Features:
* Display of tile grid outline and 'central area' region on map UI.
This can be enabled from the settings and is to allow easier debug.
We can disable this in release builds in the future. The grid shown
is the one currently in use by the GeoEngine.
The new GeoJSON layer in our maplibre UI shows that there's
potential for other debug uses.
* Support 2x2 grid in addition to 3x3 grid. The reason for this is
that the protomaps vector tiles are at zoom level 15 and not zoom
level 16. A 3x3 grid at zoom level 15 is more data than we need,
so we can now switch to using a 2x2 grid. The …
=> GeoEngine tile update cleanup

app/src/main/java/org/scottishtecharmy/soundscape/MainActivity.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GeoEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/network/ITileDAO.kt, app/src/main/java/org/scottishtecharmy/soundscape/network/ProtomapsTileClient.kt, app/src/main/java/org/scottishtecharmy/soundscape/network/SoundscapeBackendTileClient.kt, app/src/main/java/org/scottishtecharmy/soundscape/network/TileClient.kt
This change moves the soundscape-backend specific parts of TileClient out into a sub-class so that a protomaps TileClient can share the caching code.
It also removes the unused http caching from MainActivity - we no longer use the type of HTTP access that would use this cache.
=> Add caching to protomaps tile client

app/src/main/java/org/scottishtecharmy/soundscape/utils/MvtToGeoJson.kt, app/src/test/java/org/scottishtecharmy/soundscape/MvtTileTest.kt
This is so that tests can pass in the zoom level without relying on it being set correctly in ZOOM_LEVEL. This allows soundscape-backend and protomaps backend both to be  tested.
=> Allow passing in of zoom level to vectorTileToGeoJson

app/src/main/java/org/scottishtecharmy/soundscape/utils/MvtToGeoJson.kt
The first change removes some false intersections which we were creating where two line segments for the same path/road met. I had code in to do this previously, but had forgotten why it was there and had removed it.
The second change is fairly complex to look at but is simply truncating path/road strings at the tile boundary using interpolated nodes on the tile edge. The result seems pretty good and is better than the 20m of overlapping roads that we had prior to the change.
=> More MVT to GeoJSON translation work

.github/workflows/nightly.yaml, .github/workflows/tag-and-build-release.yaml, app/build.gradle.kts
We don't currently need a tile provider API key so remove it from GitHub actions and the build.gradle.kts.
=> Remove tile provider steps from GitHub actions and build file

app/src/main/java/org/scottishtecharmy/soundscape/database/local/RealmConfiguration.kt, app/src/main/java/org/scottishtecharmy/soundscape/database/local/dao/TilesDao.kt, app/src/main/java/org/scottishtecharmy/soundscape/database/local/model/TileData.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GeoEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/geojsonparser/geojson/MultiPoint.kt, app/src/main/java/org/scottishtecharmy/soundscape/geojsonparser/moshi/GeoJsonObjectMoshiAdapter.kt, app/src/main/java/org/scottishtecharmy/soundscape/utils/MvtToGeoJson.kt, app/src/main/java/org/scottishtecharmy/soundscape/utils/TileUtils.kt, app/src/test/java/org/scottishtecharmy/soundscape/GeoJsonParserTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/MvtTileTest.kt
All of the work in these commits is aimed at having `getGridFeatureCollections()` return connecting `LineStrings` at tile boundaries to join up roads and paths which meander across them. Whilst doing this work I noticed that the `Long` id from the MVT couldn't be roundtripped via JSON as JSON only supports `Int` and `Double`. As a result, the id now used internally is a `Double` which is large enough (by a factor of 10000) despite it being non-ideal.
=> Work on MVT to GeoJSON to add joining of paths/roads at tile boundaries

app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GeoEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/geojsonparser/geojson/FeatureCollection.kt
All the deduplication has already been taken care of during the MVT to GeoJSON translation and no further deduplication should be done. Because we can have multiple segments of the same OSM id (e.g. separate ones where a road crosses a tile) we actually can't de-duplicate.
=> Don't deduplicate in getGridFeatureCollections with protomaps backend

app/src/main/assets/osm-bright-gl-style/style.json, app/src/main/java/org/scottishtecharmy/soundscape/MainActivity.kt, app/src/main/java/org/scottishtecharmy/soundscape/network/ITileDAO.kt, app/src/main/java/org/scottishtecharmy/soundscape/network/ProtomapsTileClient.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/MapContainerLibre.kt, app/src/main/java/org/scottishtecharmy/soundscape/utils/TileGridUtils.kt
This change consolidates the location of the protomaps server configuration allowing it to be easily switched between cloud and local for developer testing. It also lays the groundwork for having the server URI be a secret as we now parse the `style.json` used by maplibre and dynamically insert the URL.
=> Add configuration of protomaps server to ease local testing

app/src/main/res/values-da/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-nb/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values/strings.xml
We currently only have translation strings for "Facing $direction" for "My Location" as we are pretending the user is stationary as we don't currently detect if the user is stationary, walking or in a vehicle. This PR adds the basic strings for "Heading $direction" and "Travelling $direction" in anticipation of getting the Activity Recognition API working correctly. 
"Facing" = stationary 
"Heading" = walking 
"Travelling" = in a vehicle
I'll add the "Travelling north along $road" and "Heading north along $road" strings in another PR
=> Translation strings for heading and travelling in a direction.

app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/HomeContent.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/MapViewHelper.kt
There were a couple of issues with the way in which our GUI map was rendered:
1. The icons, text and roads were very small and zooming in didn't make them larger. The fix is to set the `pixelRatio` which means that the map is now rendered as if the DPI were a quarter of it's previous value and then scaled up. This gives a slightly "soft" look, but at least everything is larger.
2. Rotating the map with the phone wasn't performant on complex map tiles. The fix is to switch to rotate only the icon showing the user location and to keep the map with North at the top. This matches the iOS behaviour.
=> Improve maplibre usability

app/build.gradle.kts
Originally this PR was written as follows:
> Since Android 13 it's been possible to set the app language from the App Info dialog for any app. Although we support as far back as Android 11, the app will still use the system configured language just not a different language for the app prior to Android 13. This change removes our in-app language configuration and leaves it to the System. It also fixes support for Brazil, UK and Canada regions where the resources were being stripped out due to not being in the list in resourceConfigurations in build.gradle.kts. The behaviour has been tested on API 35 and API 30 and both work correctly.
However, I've changed it so that it's now just the minimal change to get the regional languages working.
=> Remove trimming of resource locales from build.gradle.kts

app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt
This trivial change stops the service from shutting down when the app is closed. That behaviour came in when we added MediaSessionService and by ignoring the onTaskRemoved call we can revert to the previous behaviour.
=> Keep service alive when app is closed #305

app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GeoEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/callouts/IntersectionUtils.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/utils/CompassDirections.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/utils/FeatureTree.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/utils/IntersectionUtils.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/utils/TileUtils.kt, app/src/test/java/org/scottishtecharmy/soundscape/ComplexIntersections.kt, app/src/test/java/org/scottishtecharmy/soundscape/CrossingTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/IntersectionsTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/IntersectionsTestMvt.kt, app/src/test/java/org/scottishtecharmy/soundscape/RoundaboutsTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/StreetPreviewTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/TileUtilsTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/VisuallyCheckIntersectionLayers.kt
The main change here is to de-duplicate the intersection description code from the unit tests and GeoEngine and have a single function in a new file IntersectionUtils. This should be the same as as that which was in the ComplexIntersections unit test. A new function in the same file can then take the IntersectionDescription and turn it into a callout. The other change in that area is the start of improving the callout code to use the results of the ActivityRecognition to switch between heading, facing and travelling in the callouts.
The final change is that getNearestRoad now uses FeatureTree to perform it's searching. Not only does this improve its performance, but it allows us to search outside the FOV - the nearest road could be 0.5m behind the current FOV and searching only within the …
=> Centralize intersection description code

app/src/androidTest/java/org/scottishtecharmy/soundscape/PhotonSearchTest.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GeoEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/callouts/IntersectionUtils.kt, app/src/main/java/org/scottishtecharmy/soundscape/network/SearchProvider.kt, app/src/test/java/org/scottishtecharmy/soundscape/ComplexIntersections.kt, app/src/test/java/org/scottishtecharmy/soundscape/IntersectionsTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/IntersectionsTestMvt.kt
I'd missed this by mistake when refactoring - this change restores the 'X road ahead' prior to describing an intersection. However, it does bring up a question:
In the previous commit I switched nearestRoad to be the actual nearest
road, and not the nearest within the FOV. For reporting 'X road ahead' I think that we do want the road in the FOV so I calculate both. It seems 'no worse', but requires some more thought. However, the code is all in one place now so should be easier to consider.
=> Add back in nearest road for Ahead of Me

app/src/main/java/org/scottishtecharmy/soundscape/geoengine/mvttranslation/InterpolatedPointsJoiner.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/mvttranslation/MvtToGeoJson.kt
The calculations that translate the integer relative tile coordinates into fractional tile coordinates now place the sample point in the middle of the sample range i.e. on the half pixel. This fixes the calculations made for the interpolated points where lines cross tile boundaries as the tile boundaries are no longer coincident with the sample points.
=> Adjust coordinate calculations for MVT translation by 0.5 pixel

app/src/main/java/org/scottishtecharmy/soundscape/SoundscapeServiceConnection.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GeoEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GridState.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/ProtomapsGridState.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/SoundscapeBackendGridState.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/StreetPreview.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/callouts/IntersectionUtils.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/utils/FeatureTree.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/utils/GeoUtils.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/utils/Quadrant.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/utils/TileUtils.kt, app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/home/HomeViewModel.kt, app/src/test/java/org/scottishtecharmy/soundscape/BusStopTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/ComplexIntersections.kt, app/src/test/java/org/scottishtecharmy/soundscape/CrossingTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/DijkstraTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/IntersectionsTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/IntersectionsTestMvt.kt, app/src/test/java/org/scottishtecharmy/soundscape/MarkersTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/MvtTileTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/RoundaboutsTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/SearchTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/StreetPreviewTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/TileUtilsTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/VisuallyCheckIntersectionLayers.kt, app/src/test/java/org/scottishtecharmy/soundscape/VisuallyCheckOutput.kt
The GeoEngine creates either a ProtomapsGridState or a SoundscapeBackendGridState which hide away creating the FeatureTrees from data downloaded from those servers. The FeatureTrees can be accessed via getFeatureTree or via various search functions which have been moved into the GridState class. These all now call checkContext which ensures that the code is being called on the single thread allowed to access the FeatureTrees.
=> Create GridState class to hold tile grid data and functionality

app/src/main/cpp/AudioBeacon.cpp, app/src/main/cpp/AudioEngine.cpp, app/src/main/cpp/AudioEngine.h, app/src/main/cpp/GeoUtils.h
Prior to this change the code was just using longitude and latitude as x,y coordinates within FMOD. That's fine near the equator where 1 degree is a similar distance in each direction, but moving away from the equator 1 degree of latitude shrinks (down to zero at the poles!). This change uses a very simple equirectangular projection to translate longitude and latitude into an x,y system for FMOD. The origin used is the first coordinate converted which will be either the current location, or the locatoin of a beacon. Ensuring that the origin is relatively close means that the projection is accurate enough for our purposes.
To test the improvement, create an audio beacon and point directly at it on the UI map. The audio should be playing evenly out of left and right on your headphones.
=> Fix coordinate system used within FMOD to preserve direction

app/src/main/cpp/AudioEngine.cpp, app/src/main/cpp/AudioEngine.h, app/src/main/java/org/scottishtecharmy/soundscape/audio/AudioEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/audio/NativeAudioEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GeoEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt
The immediately useful change here is that the auto callout code now calls isAudioEngineBusy before generating any more output. If there is already text-to-speech playing out, then it won't generate any more. This aims to prevent a backup of audio description.
The other change is the start of a callback when audio playout completes, but so far this is only within the C++ code and doesn't make it back to the kotlin code.
=> Add some flow control for text-to-speech and callouts

app/src/main/AndroidManifest.xml, app/src/main/java/org/scottishtecharmy/soundscape/SoundscapeIntents.kt, app/src/main/java/org/scottishtecharmy/soundscape/geojsonparser/geojson/LngLatAlt.kt
This is based on a sample file from when a route was exported from the iOS app. This commit registers application/json for the app and then tries to decode it with the assumption that it matches the format in the sample file. RouteData and RoutePoint don't have fields for all of those in the JSON, though we may add them in future.
With this code in place the shared file can be 'opened' on the phone and it will run Soundscape and import the route.
=> Initial decode of iOS exported route and import into database

app/src/main/java/org/scottishtecharmy/soundscape/MainActivity.kt, app/src/main/java/org/scottishtecharmy/soundscape/SoundscapeServiceConnection.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/DrawerContent.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/HomeRoutes.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/HomeScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/HelpScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/screens/routedetailsscreen/RouteDetailsScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/screens/routedetailsscreen/RouteDetailsViewModel.kt, app/src/main/java/org/scottishtecharmy/soundscape/services/RoutePlayer.kt, app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt, app/src/screenshotTest/kotlin/org/scottishtecharmy/soundscape/PreviewTest.kt
Two independent commits here, one to wire up RoutePlayer to "Play Route" and the other to add all of the iOS based help resources to the drawer menu.
=> Wire up RoutePlayer and add Help text in menu

app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GeoEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/StreetPreview.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/UserGeometry.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/callouts/AutoCallout.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/callouts/IntersectionUtils.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/filters/LocationUpdateFilter.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/filters/TrackedCallout.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/utils/TileUtils.kt, app/src/main/java/org/scottishtecharmy/soundscape/geojsonparser/geojson/LngLatAlt.kt, app/src/main/java/org/scottishtecharmy/soundscape/locationprovider/LocationProvider.kt, app/src/test/java/org/scottishtecharmy/soundscape/BusStopTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/ComplexIntersections.kt, app/src/test/java/org/scottishtecharmy/soundscape/CrossingTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/IntersectionsTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/IntersectionsTestMvt.kt, app/src/test/java/org/scottishtecharmy/soundscape/MarkersTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/PoiTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/RoundaboutsTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/StreetPreviewTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/TileUtilsTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/VisuallyCheckIntersectionLayers.kt, app/src/test/java/org/scottishtecharmy/soundscape/VisuallyCheckOutput.kt, app/src/test/java/org/scottishtecharmy/soundscape/filters/CalloutHistoryTest.kt
The iOS app has three current headings which I think correspond to:
1. The phone direction
2. The direction of travel
3. The direction from head tracking
This PR adds direction of travel, currently taking it unfiltered from the location provider. The `heading` function is now called to return one of those headings (we don't support head tracking yet), and it's based on the `HeadingMode` of the `UserGeometry` instance. `Auto` mode will pick the travel direction if there is one, otherwise it will use the phone direction. Callers which want the phone direction can specify `HeadingMode.Phone` when creating the `UserGeometry`.
=> Add travel heading to UserGeometry and move into its own file

app/src/androidTest/java/org/scottishtecharmy/soundscape/AudioEngineTest.kt, app/src/main/java/org/scottishtecharmy/soundscape/SoundscapeIntents.kt, app/src/main/java/org/scottishtecharmy/soundscape/SoundscapeServiceConnection.kt, app/src/main/java/org/scottishtecharmy/soundscape/audio/AudioEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/audio/NativeAudioEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/components/LocationItem.kt, app/src/main/java/org/scottishtecharmy/soundscape/database/local/model/RouteData.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GeoEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/geojsonparser/geojson/LngLatAlt.kt, app/src/main/java/org/scottishtecharmy/soundscape/locationprovider/GpxDrivenProvider.kt, app/src/main/java/org/scottishtecharmy/soundscape/locationprovider/StaticLocationProvider.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/HomeScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/data/LocationDescription.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/Home.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/HomeContent.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/MapContainerLibre.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/locationDetails/LocationDetailsScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/screens/markersscreen/MarkersScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/screens/markersscreen/MarkersScreenList.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/screens/markersscreen/MarkersViewModel.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/onboarding/audiobeacons/AudioBeaconsViewModel.kt, app/src/main/java/org/scottishtecharmy/soundscape/services/RoutePlayer.kt, app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt, app/src/main/java/org/scottishtecharmy/soundscape/utils/LocationExt.kt, app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/LocationDetailsViewModel.kt, app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/home/HomeState.kt, app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/home/HomeViewModel.kt
There were too many pairs of longitude and latitude doubles being passed around in the UI instead of using the data class LngLatAlt. This commit sorts this out.
=> Move APIs with doubles for lng/lat to use LngLatAlt instead.

app/src/androidTest/java/org/scottishtecharmy/soundscape/AudioEngineTest.kt, app/src/main/cpp/AudioBeacon.cpp, app/src/main/cpp/AudioBeaconBuffer.cpp, app/src/main/cpp/AudioBeaconBuffer.h
The Earcon code was a bit confused and resulted in audio positioning not working. This change makes EarconSource operate in the same was as BeaconBuffer and TextToSpeechSource. It creates the sound in FMOD and then leaves the rest up to PositionedAudio::InitFmodSound. The only additional work that EarconSource has to do, is that it has to monitor for the playback completing so that it can mark the Earcon as EOF.
The other minor change is to start all audio paused, then set its position, and then take it out of pause to start playing.
=> Earcon audio positioning fixes

app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GeoEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GridState.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/StreetPreview.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/utils/FeatureTree.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/Home.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/HomeContent.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/StreetPreviewUi.kt, app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt, app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/home/HomeState.kt
Prior to this change, trying to use StreetPreview to a far away location
was broken and would jump to the edge of the current TileGrid instead. This
change causes the UI to wait for the new TileGrid to be uploaded before
jumping to the nearest road and providing a choice for the user.
=> StreetPreview UI change to allow for TileGrid update

app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GeoEngine.kt
Retrofit throws exceptions on a timeout, so catch them and return null. This fixes crash on Firebase robo test from at 16:35 on 10/02/2025.
=> Catch timeout exceptions when contacting photon server

app/src/main/java/org/scottishtecharmy/soundscape/services/RoutePlayer.kt
The nightly build on 13/02/2025 at 05:46 ran a Robo test which hit an assert because it was starting playback of a route which had no waypoints. This commit removes the assert and simply ignores the request to start playback.
=> Fix assert when playing route with no Waypoints

app/src/main/java/org/scottishtecharmy/soundscape/SoundscapeIntents.kt, app/src/main/java/org/scottishtecharmy/soundscape/components/LocationItem.kt, app/src/main/java/org/scottishtecharmy/soundscape/components/MainSearchBar.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GeoEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/HomeScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/data/LocationDescription.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/Home.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/HomeContent.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/locationDetails/LocationDetailsScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/locationDetails/SaveAndEditMarkerDialog.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/screens/MarkersAndRoutesScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/screens/addandeditroutescreen/AddAndEditRouteScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/screens/addandeditroutescreen/AddAndEditRouteViewModel.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/screens/addandeditroutescreen/AddWaypointsDialog.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/screens/addandeditroutescreen/AddWaypointsList.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/screens/addandeditroutescreen/ReorderableLocationList.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/screens/markersscreen/MarkersScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/screens/markersscreen/MarkersScreenList.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/screens/markersscreen/MarkersUiState.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/screens/markersscreen/MarkersViewModel.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/screens/routedetailsscreen/RouteDetailsScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/utils/LocationExt.kt, app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/LocationDetailsViewModel.kt, app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/home/HomeViewModel.kt
Instead of storing the distance string, we calculate as and when it's required by the UI. This should enable us to update the values as the user moves.
=> Rationalize LocationDescription by removing distance string

app/src/main/java/org/scottishtecharmy/soundscape/SoundscapeIntents.kt, app/src/main/java/org/scottishtecharmy/soundscape/components/LocationItem.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/HomeScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/locationDetails/LocationDetailsScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/screens/addandeditroutescreen/AddAndEditRouteScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/screens/addandeditroutescreen/AddAndEditRouteViewModel.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/screens/addandeditroutescreen/AddWaypointsList.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/screens/addandeditroutescreen/ReorderableLocationList.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/screens/markersscreen/MarkersScreenList.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/screens/routedetailsscreen/RouteDetailsScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/screens/routesscreen/RoutesScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/screens/routesscreen/RoutesScreenList.kt, app/src/main/java/org/scottishtecharmy/soundscape/services/RoutePlayer.kt
Importing a route via an intent now goes via the add route screen. This passes JSON describing the route from the intent into the screen which then displays it and allows adding it to the database.
There are also numerous amateur tweaks to improve the click sites within the markers/routes UI. Plenty still to do.
=> Import route now goes via Add Route Screen and some UI tweaking

app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/StreetPreviewUi.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/locationDetails/LocationDetailsScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/settings/Settings.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/components/CustomFloatingActionButton.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/components/CustomTextButton.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/onboarding/audiobeacons/AudioBeacons.kt, app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/SettingsViewModel.kt, app/src/main/res/values/strings.xml
The beacon type strings are returned from C++. This change adds in a mapping function to resource ids which are then used in the UI.
=> Add translations of beacon types to UI - #175

app/build.gradle.kts, app/proguard-rules.pro
Two new proguard rules were required. One to preserve FMOD library and the other for protobuf generated files. With these in place the shrunk app now runs successfully.
=> Enable minify and shrink on release builds

app/src/main/java/org/scottishtecharmy/soundscape/MainActivity.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GeoEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/ProtomapsGridState.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/utils/TileUtils.kt, app/src/test/java/org/scottishtecharmy/soundscape/MvtTileTest.kt
I refactored mergeAllPolygonsInFeatureCollection a little so that it would merge all duplicates of a polygon into a single one. It seems to work well, so I've re-enabled it to see what happens.
=> Reinstate Adam's polygon merging code with a bit of refactoring

app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GeoEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/onboarding/language/LanguageViewModel.kt
Two fixes here:
Language selection - the code to show the default language in the onboarding screen was only using the phone language and not the country. As a result on UK English phones it was showing English (US) as the selected language. This change adds the country into the mix. If the country isn't supported, the language selected will be the first in the list i.e. French from France, non-UK English and Portuguese from Portugal.
Travelling by train!
=> Use country as well as language when matching locale

app/src/androidTest/java/org/scottishtecharmy/soundscape/MvtPerformanceTest.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GridState.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/ProtomapsGridState.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/SoundscapeBackendGridState.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/mvttranslation/IntersectionDetection.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/mvttranslation/MvtToGeoJson.kt, app/src/main/java/org/scottishtecharmy/soundscape/network/ProtomapsTileClient.kt, app/src/main/java/org/scottishtecharmy/soundscape/network/SoundscapeBackendTileClient.kt, app/src/main/java/org/scottishtecharmy/soundscape/network/TileClient.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/placesnearby/PlacesNearbyList.kt, q
PlacesNearby can display a list of intersections. Their naming was done just to ease debugging and so wasn't particularly tidy. This change means that we now only name intersections which contain at least one named road i.e. no path/service type intersections. The named roads are listed alphabetically in the intersection name.
=> Improve intersection naming now that they appear in the UI

app/src/androidTest/java/org/scottishtecharmy/soundscape/MvtPerformanceTest.kt, app/src/main/java/org/scottishtecharmy/soundscape/MainActivity.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GeoEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/callouts/IntersectionUtils.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/filters/MapMatchFilter.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/utils/GpxRecorder.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/utils/RoutingUtils.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/DrawerContent.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/HomeScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/Home.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/settings/Settings.kt, app/src/main/res/values/strings.xml, app/src/test/java/org/scottishtecharmy/soundscape/DijkstraTest.kt
If the "Enable recording of travel" setting is switched on, then each GPS location is saved to a buffer. The buffer stores up to the last hour of locations and those can be shared to another application via the "Share recording of travel" option in the menu. No location is shared otherwise, so it's purely a user decision. The aim of the shared GPX file is to aid debugging. With the option enabled, a user can share their movement if there's some behaviour that they didn't expect.
=> Switch to using `last buffer` style GPX recording and more MapMatchFilter tweaks

app/src/main/cpp/GeoUtils.h
This was a trivial mistake when porting the Kotlin function over to C++. Easy fix.
=> Fix intersection callout audio direction bug #496

app/src/main/java/org/scottishtecharmy/soundscape/geoengine/filters/MapMatchFilter.kt
directionOnLine was being checked against an absolute value, but the number is a proportion of a Way segment which could be of any length. Really it just needs to be checked against being the reset value of 0.0.
=> Tidy up direction change detection in MapMatchFilter

app/src/androidTest/java/org/scottishtecharmy/soundscape/MvtPerformanceTest.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GeoEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GridState.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/StreetPreview.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/callouts/IntersectionUtils.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/utils/FeatureTree.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/utils/TileUtils.kt, app/src/test/java/org/scottishtecharmy/soundscape/BusStopTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/ComplexIntersections.kt, app/src/test/java/org/scottishtecharmy/soundscape/CrossingTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/DijkstraTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/MvtTileTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/TileUtilsTest.kt, app/src/test/java/org/scottishtecharmy/soundscape/VisuallyCheckIntersectionLayers.kt
The previous code had a few drawbacks which this change fixes:
* Ways weren't followed to their ends, so when they cross a bridge, go
down steps or cross a tile boundary the name confection was happening at
that point instead of at the furthest known extent. The code now uses
FollowWays to get a better start and end location for confecting the names.
* Ways that cross into polygons such as parks weren't being well described
because both ends were being marked as in the park. The code now takes more
care when a Way starts and ends in/out of a Polygon to ensure that the
later feature tree searches don't end up masking that fact. It can also use
features that are within large polygons such as parks, so that paths within
parks can be named as "to cafe" etc.
* The POI used to confect were only …
=> Improve name confection for un-named Ways

app/src/main/java/org/scottishtecharmy/soundscape/geoengine/utils/rulers/CheapRuler.kt
distanceToLineString wasn't using values it had already saved which was throwing up a lint warning. Fixing it should make the code even more efficient.
=> Fix distanceToLineString in CheapRuler to avoid lint warnings

app/src/main/assets/osm-liberty-accessible/originalStyle.json, app/src/main/java/org/scottishtecharmy/soundscape/MainActivity.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GeoEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/MapContainerLibre.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/locationDetails/LocationDetailsScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/home/settings/Settings.kt, app/src/main/res/values/strings.xml
The OSM Liberty map styling is excellent, but lacks contrast. This is the start of customizing it with the aim of better supporting visually impaired users. The map is enabled via the Settings "Enable accessible map styling". With that option enabled, the styling will switch based on the light/dark theme with higher contrast and larger text labels. More work is required before we turn this on as the default.
=> Add setting to switch to alternate map styling

app/src/main/assets/osm-liberty-accessible/originalStyle.json, app/src/main/assets/osm-liberty-accessible/style.json
With these in place, the fastlink busway along the Clyde and the Cambridge guided busway are both rendered correctly on the map. This addresses #530.
=> Add busway and bus_guideway to our GUI map styling

app/proguard-rules.pro, app/src/main/java/org/scottishtecharmy/soundscape/screens/onboarding/audiobeacons/AudioBeaconsViewModel.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/onboarding/hearing/HearingViewModel.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/onboarding/language/LanguageViewModel.kt
This is important as we have to uninstall the audio focus callback. Also change the proguard rules to prevent our callback function from being obfusctated or removed.
=> Tidyup audio engines used in onboarding screens

app/src/main/java/org/scottishtecharmy/soundscape/audio/NativeAudioEngine.kt
I think this leak must have been around for a little while, but LeakCanary only started reporting it recently. A simple fix, remove the callback before destroying the TextToSpeech engine.
=> Fix memory leak from TextToSpeech setOnUtteranceProgressListener

app/build.gradle.kts, gradle/libs.versions.toml
There's a one off crash on OnePlus Pro8 phones which look to be caused by this library initializing. It's only used in development, so let's just remove it from the regular build.
=> Remove libs.androidx.benchmark.common library from the build

app/src/main/java/org/scottishtecharmy/soundscape/MainActivity.kt, app/src/main/java/org/scottishtecharmy/soundscape/audio/TtsEngine.kt, app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt, docs/release-notes.md, docs/testing/test-instructions.md
If startForeground fails we now start the geoEngine anyway. And then in the next onResume we try startForeground again. There's also some debug code to make it 'fail' the first time to check the error paths. If there's no onResume within 10 seconds then the app will still shutdown, but not due to a crash. I think that's as good as we can do for now. The Crashlytics logging should allow us to check that any failures are a due to this behaviour.
=> More crashlytics logging aimed and changes aimed at foreground start

app/src/main/java/org/scottishtecharmy/soundscape/screens/home/locationDetails/LocationDetailsScreen.kt, app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/screens/markersscreen/MarkersScreen.kt
Two approaches here - in the MarkersScreen we display the HTML with Markdown as intended. In the LocationDetailsScreen we just pass the plain text version into the Intent.
=> Fix markdown seeping into UI

app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GridState.kt, app/src/main/java/org/scottishtecharmy/soundscape/geoengine/mvttranslation/WayGenerator.kt
As a final stage after the grid has been constructed, go through all of the intersections updating their names to reflect any confections that took place.
=> Use confected names when constructing intersection names
