Scottish-Tech-Army/Soundscape-Android

app/src/main/res/values/strings.xml

Testing new repo and GitHub workflow

Update "app_name" to Soundscape from SoundscapeAlpha

---

app/src/main/java/org/scottishtecharmy/soundscape/geojsonparser/moshi/GeoJsonObjectMoshiAdapter.kt

Not really a fix more of a shooting myself in the foot kind of bodge which will probably come back to bite me.

"Fix" unchecked cast warnings.

---

app/src/main/java/org/scottishtecharmy/soundscape/geojsonparser/moshi/LineStringJsonAdapter.kt
app/src/main/java/org/scottishtecharmy/soundscape/geojsonparser/moshi/LngLatAltMoshiAdapter.kt

Tidied up code as per IDE suggestions

Fix moshi adapter lint warnings for LineString and LngLatAlt

---

app/src/main/java/org/scottishtecharmy/soundscape/screens/Home.kt
app/src/main/java/org/scottishtecharmy/soundscape/screens/navigation/NavGraph.kt
app/src/main/java/org/scottishtecharmy/soundscape/screens/onboarding/AudioBeacons.kt
app/src/main/java/org/scottishtecharmy/soundscape/screens/onboarding/Navigating.kt
app/src/main/java/org/scottishtecharmy/soundscape/screens/permissions/SoundscapePermissionCheck.kt

Unfortunately, we will have a few lint warnings poking up their heads until we get all the onboarding screens written and get to our main UI.

Fix lint warnings as far as possible

---

app/src/androidTest/java/org/scottishtecharmy/soundscape/WelcomeScreenTest.kt

Putting this on here so we can look at putting UI tests on Firebase or something.

Simple first UI test

---

.github/workflows/run-tests.yaml
app/google-services.json

Google secrets cannot be used in run-test as the user it runs under doesn't necessarily have permissions to access them. Add a mock google-services.json for this situation.

Add write permissions to run-test

---

docs/README.md
docs/actions.md

Some initial documentation describing the GitHub actions and the various secrets that they use.

Add doc describing GitHub actions

---

app/src/main/AndroidManifest.xml
app/src/main/cpp/fmod/api/core/inc/fmod_codec.h
app/src/main/java/org/scottishtecharmy/soundscape/MainActivity.kt
app/src/main/java/org/scottishtecharmy/soundscape/SoundscapeApplication.kt
app/src/main/java/org/scottishtecharmy/soundscape/audio/NativeAudioEngine.kt
app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt

The first couple of commits tidy up lint warnings.
The other three were changes that I'd previously committed to my own SoundscapeAlpha and am now landing here.

Tidy up lint warnings and land some old work

---

app/src/androidTest/java/org/scottishtecharmy/soundscape/GpxTest.kt

The GpxTest tests were reliant on the order in which they were run. The parsing tests were populating the inMemory database and then the database tests were testing that. However, when Firebase runs the test the database from previous tests doesn't exist and so the tests were failing. This change makes each of the tests standalone without dependency on other tests.

Fix GpxTest tests to all run standalone without dependency on each other

---

.github/workflows/build-app.yaml
.github/workflows/nightly.yaml

The new nightly build github action runs at 05:30 if there has been a commit within the last 24 hours. It builds a debug package and runs the Instrumentation tests and a Robo test on Firebase.

Add nightly build github action

---

app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt
app/src/main/java/org/scottishtecharmy/soundscape/utils/TileUtils.kt

default values in getTilesForRegion()

Clear up null pointer exception from Soundscape service and put 

---

app/src/main/cpp/AudioEngine.cpp
app/src/main/java/org/scottishtecharmy/soundscape/screens/onboarding/AudioBeacons.kt

Update beacon names to match translation strings.

Beacon names

---

app/src/main/java/org/scottishtecharmy/soundscape/screens/onboarding/Navigating.kt
app/src/main/java/org/scottishtecharmy/soundscape/screens/permissions/SoundscapePermissionCheck.kt
app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/PermissionsViewModel.kt

TODO Rationales and handling denied permissions

Moved permissions requests to Navigate.kt

---

.github/workflows/nightly.yaml
app/build.gradle.kts
app/src/main/java/org/scottishtecharmy/soundscape/screens/Home.kt
app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/HomeViewModel.kt
gradle/libs.versions.toml

A cleanup of the libraries that we use.
Change nightly builds to run instrumentation tests on APIs 30,31 and 34.
Change the water back to blue on the maps!

Upgrade and improve

---

app/src/main/java/org/scottishtecharmy/soundscape/screens/Home.kt
app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt
app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/MyLocationViewModel.kt

As discussed setting up the UI -> ViewModel -> Service structure

Setup "My Location" button

---

app/build.gradle.kts
build.gradle.kts
gradle/libs.versions.toml

This allows tracking of app performance over time which may be useful.

Enable support for Firebase performance monitoring

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/scottishtecharmy/soundscape/MainActivity.kt
app/src/main/java/org/scottishtecharmy/soundscape/SoundscapeServiceConnection.kt
app/src/main/java/org/scottishtecharmy/soundscape/audio/NativeAudioEngine.kt
app/src/main/java/org/scottishtecharmy/soundscape/locationprovider/LocationProvider.kt
app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt
app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/HomeViewModel.kt

The location and orientation providers have been moved out into a separate package. A new StaticLocationProvider has been added which allows faking up a fixed position. Passing in a geo URI will activate this behaviour (for now)

Move around location and orientation provider code to allow extending

---

app/src/main/java/org/scottishtecharmy/soundscape/audio/NativeAudioEngine.kt
app/src/main/java/org/scottishtecharmy/soundscape/locationprovider/LocationProvider.kt

A fix for no location and for setting the text to speech locale correctly.

Text to speech fixes

---

app/src/main/java/org/scottishtecharmy/soundscape/kalman/KalmanFilter.kt
app/src/main/java/org/scottishtecharmy/soundscape/locationprovider/LocationProvider.kt
app/src/test/java/org/scottishtecharmy/soundscape/KalmanFilterTest.kt

This is loosely based on the Soundscape iOS version. The test isn't very scientific and could probably use tightening up.

Add Kalman filter to smooth location

---

app/src/main/AndroidManifest.xml

This simply required an addition to the manifest of the INTENT_ACTION_TTS_SERVICE.

Fix Text to Speech at API 30

---

app/build.gradle.kts
app/src/main/java/org/scottishtecharmy/soundscape/screens/Home.kt
app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/DrawerViewModel.kt
gradle/libs.versions.toml

This seems fairly standard stuff, but it's not possible to easily test without building a release and putting it on the internal test track.

First attempt at in app review

---

app/src/main/java/org/scottishtecharmy/soundscape/screens/Home.kt
app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/DrawerViewModel.kt

This looks like it might work, still needs tested via Play Store though.

Rate app second attempt with correct activity passed in

---

app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt

Not nearly finished yet as need to check for duplicate features and a lot of other things!!

Added a 3x3 grid rather than a single tile. 

---

app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt

The device must be within 30 meters of the intersection and the intersection within the Field Of View. It will tell you how far away the intersection is. Still to do names of roads that make up intersection and relative direction of those roads

Added intersection detection to the Ahead Of Me button. 

---

app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt

Still need to do the directions of the roads that make up the intersection

Detect the road names that make up the intersection in the field of view

---

app/src/main/java/org/scottishtecharmy/soundscape/mapui/RamaniMapUi.kt
app/src/main/java/org/scottishtecharmy/soundscape/screens/home/LocationDetails.kt
app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/LocationDetailsViewModel.kt

Creates an audio beacon at the location described.

Add button to create beacon on LocationDetails page

---

app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt
app/src/main/java/org/scottishtecharmy/soundscape/utils/CompassDirections.kt
app/src/main/res/values-da/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-el/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fi/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-nb/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-pt/strings.xml
app/src/main/res/values-sv/strings.xml
app/src/main/res/values/strings.xml

and their translation strings.

Relative direction labels "Ahead", "Ahead Right", etc. 

---

app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt

ending in numbers getting merged with the distance away from current location.

Fix issue with Features that have names 

---

app/src/main/java/org/scottishtecharmy/soundscape/screens/home/locationDetails/LocationDetailsScreen.kt
app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/components/CustomAppBar.kt
app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/components/CustomAppBarTitle.kt
app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/components/IconWithTextButton.kt
app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/components/MarkersAndRoutesAppBar.kt
app/src/main/java/org/scottishtecharmy/soundscape/screens/markers_routes/screens/AddRouteScreen.kt
app/src/main/java/org/scottishtecharmy/soundscape/ui/theme/Theme.kt
app/src/main/java/org/scottishtecharmy/soundscape/ui/theme/Type.kt

create fully custom app bar to scale properly with font, and use material theme typography for app bar

create fully custom app bar to scale properly with font, and use material theme typography for app bar

---

app/src/androidTest/java/org/scottishtecharmy/soundscape/AudioEngineTest.kt
app/src/main/cpp/AudioBeacon.cpp
app/src/main/java/org/scottishtecharmy/soundscape/audio/AudioEngine.kt
app/src/main/java/org/scottishtecharmy/soundscape/audio/NativeAudioEngine.kt
app/src/main/java/org/scottishtecharmy/soundscape/services/RoutePlayer.kt
app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt
app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/HearingViewModel.kt
docs/README.md
docs/tricky-locations.md

Two changes in this PR, the first is to allow easy text to speech without specifying a location. And the other is a new document to store locations that are interesting to test with.

Alter `createTextToSpeech` so as to default to non-positioned audio

---

app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt

The code here is only temporary, but here are some fixes to stop it crashing.

Fixup POC text to speech crashes

---

docs/README.md
docs/release-notes.md
docs/testing.md

I don't know how best to write the testing doc. The release notes cover lots of the features already. I think a QA/test person might prefer a database of features and how to test them - I require some advice!

Update release notes and start testing doc

---

.github/workflows/build-app.yaml
app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeMediaSessionCallback.kt

Reverts Scottish-Tech-Army/Soundscape-Android#219
I couldn't easily figure out the permissions required. Needs some more work.

Revert "Testing release build upload to PlayStore"

---

app/src/test/java/org/scottishtecharmy/soundscape/DijkstraTest.kt

This is based on a GeoJSON FeatureCollection containing roads as LineStrings. It uses the Dijkstra algorithm to find the shortest path and is quite simple as we are providing routing information based on roads to pedestrian users so we don't need to care about one way streets, roadworks, etc.

Proof of concept for local routing  

---

app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GeoEngine.kt

Handle exceptions due to lack of network, and ensure that we retry if any tiles fail to be updated.

Improve error handling when updating tile grid

---

app/src/main/java/org/scottishtecharmy/soundscape/utils/MvtToGeoJson.kt

Code wasn't actually setting the name having figured out what it was.

Fix errors in previous commit

---

app/src/main/res/values-da/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-el/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fi/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-ja/strings.xml
app/src/main/res/values-nb/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-pt/strings.xml
app/src/main/res/values-sv/strings.xml
app/src/main/res/values/strings.xml

and "Heading north along $road"

Translation strings for "Travelling north along $road" 

---

app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GeoEngine.kt
app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GridState.kt
app/src/main/java/org/scottishtecharmy/soundscape/geoengine/ProtomapsGridState.kt
app/src/main/java/org/scottishtecharmy/soundscape/geoengine/SoundscapeBackendGridState.kt
app/src/main/java/org/scottishtecharmy/soundscape/geoengine/StreetPreview.kt
app/src/main/java/org/scottishtecharmy/soundscape/geoengine/callouts/IntersectionUtils.kt
app/src/main/java/org/scottishtecharmy/soundscape/geoengine/filters/LocationUpdateFilter.kt
app/src/main/java/org/scottishtecharmy/soundscape/geoengine/filters/TrackedCallout.kt
app/src/main/java/org/scottishtecharmy/soundscape/geoengine/utils/FeatureTree.kt
app/src/main/java/org/scottishtecharmy/soundscape/geoengine/utils/GeoUtils.kt
app/src/main/java/org/scottishtecharmy/soundscape/geoengine/utils/ResourceMapper.kt
app/src/main/java/org/scottishtecharmy/soundscape/geoengine/utils/TileUtils.kt
app/src/main/java/org/scottishtecharmy/soundscape/geojsonparser/geojson/LngLatAlt.kt
app/src/main/java/org/scottishtecharmy/soundscape/locationprovider/LocationProvider.kt
app/src/main/res/values/strings.xml
app/src/test/java/org/scottishtecharmy/soundscape/GeoUtilsTest.kt
app/src/test/java/org/scottishtecharmy/soundscape/MarkersTest.kt
app/src/test/java/org/scottishtecharmy/soundscape/MvtTileTest.kt
app/src/test/java/org/scottishtecharmy/soundscape/PoiTest.kt
app/src/test/java/org/scottishtecharmy/soundscape/RoundaboutsTest.kt
app/src/test/java/org/scottishtecharmy/soundscape/StreetPreviewTest.kt
app/src/test/java/org/scottishtecharmy/soundscape/TileUtilsTest.kt
app/src/test/java/org/scottishtecharmy/soundscape/VisuallyCheckIntersectionLayers.kt
app/src/test/java/org/scottishtecharmy/soundscape/VisuallyCheckOutput.kt
app/src/test/java/org/scottishtecharmy/soundscape/filters/CalloutHistoryTest.kt

Lengthy description in commits...

More refactoring of GeoEngine code

---

app/build.gradle.kts
app/src/main/java/org/scottishtecharmy/soundscape/screens/home/DrawerContent.kt
app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/HelpScreen.kt
app/src/main/res/values/strings.xml
gradle/libs.versions.toml

This is a reasonably comprehensive list of third party libraries that are used, though perhaps we need a Google acknowledgement too? I found it almost impossible to find an app that followed the Apache license correctly and provided attribution.

Add About information for third party licenses

---

app/src/main/java/org/scottishtecharmy/soundscape/SoundscapeServiceConnection.kt
app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GeoEngine.kt
app/src/main/java/org/scottishtecharmy/soundscape/geoengine/StreetPreview.kt
app/src/main/java/org/scottishtecharmy/soundscape/geoengine/utils/GeoUtils.kt
app/src/main/java/org/scottishtecharmy/soundscape/screens/home/HomeScreen.kt
app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/Home.kt
app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/HomeContent.kt
app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/StreetPreviewUi.kt
app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt
app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/home/HomeState.kt
app/src/main/java/org/scottishtecharmy/soundscape/viewmodels/home/HomeViewModel.kt

The direction choices are now provided as a flow to the UI which can change depending on the heading and choices. Simple buttons for now.

Move towards better StreetPreview UI

---

app/src/main/java/org/scottishtecharmy/soundscape/MainActivity.kt
app/src/main/java/org/scottishtecharmy/soundscape/screens/home/HomeRoutes.kt
app/src/main/java/org/scottishtecharmy/soundscape/screens/home/HomeScreen.kt
app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/Home.kt
app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/SleepScreen.kt

Add a full screen sleep. Hitting wake up now or swiping back comes out of sleep. The UI is 'basic', but it's all hooked up to the right actions.

Start sleep screen as per #137

---

app/src/androidTest/java/org/scottishtecharmy/soundscape/AudioEngineTest.kt
app/src/main/cpp/AudioBeacon.cpp
app/src/main/cpp/AudioBeacon.h
app/src/main/cpp/AudioBeaconBuffer.cpp
app/src/main/cpp/AudioBeaconBuffer.h
app/src/main/cpp/AudioEngine.cpp
app/src/main/cpp/AudioEngine.h
app/src/main/cpp/GeoUtils.h
app/src/main/java/org/scottishtecharmy/soundscape/audio/AudioEngine.kt
app/src/main/java/org/scottishtecharmy/soundscape/audio/NativeAudioEngine.kt
app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GeoEngine.kt
app/src/main/java/org/scottishtecharmy/soundscape/geoengine/UserGeometry.kt
app/src/main/java/org/scottishtecharmy/soundscape/geoengine/callouts/AutoCallout.kt
app/src/main/java/org/scottishtecharmy/soundscape/geoengine/callouts/IntersectionUtils.kt
app/src/main/java/org/scottishtecharmy/soundscape/locationprovider/AndroidDirectionProvider.kt
app/src/main/java/org/scottishtecharmy/soundscape/locationprovider/DirectionProvider.kt
app/src/main/java/org/scottishtecharmy/soundscape/screens/onboarding/hearing/HearingViewModel.kt
app/src/main/java/org/scottishtecharmy/soundscape/services/RoutePlayer.kt
app/src/main/java/org/scottishtecharmy/soundscape/services/SoundscapeService.kt

With these changes we should now be capable of head relative callouts e.g. road to the left, road to the right. Also, the audio engine should now be using the same logic for `presentationHeading` as iOS used. More details in the commits.

Continued work on iOS heading and audio presentation

---

app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GeoEngine.kt
app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GridState.kt
app/src/main/java/org/scottishtecharmy/soundscape/geoengine/ProtomapsGridState.kt
app/src/main/java/org/scottishtecharmy/soundscape/geoengine/SoundscapeBackendGridState.kt

It's timing out constantly, and there's some re-design required to make the UI reponsive.

Disable photon reverse geocoding for now

---

.github/workflows/tag-and-build-release.yaml
app/build.gradle.kts

This reverts commit 2afb2726b356c7c14d91186f4449de01681ebcc6.
More testing on this configuration is required...

Revert "Enable minify and shrink on release builds"

---

app/src/main/java/org/scottishtecharmy/soundscape/screens/home/HomeScreen.kt

Also, remember the functions so that they are only initialized when viewModel changes.

Fix missing viewmodel in RouteFunctions initialization

---

app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GeoEngine.kt
app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GridState.kt
app/src/main/java/org/scottishtecharmy/soundscape/geoengine/UserGeometry.kt
docs/mapping.md
docs/release-notes.md

AheadOfMe calls out first 5 POI in the direction that the user is heading.

Make AheadOfMe behave like iOS

---

app/src/main/java/org/scottishtecharmy/soundscape/geoengine/mvttranslation/MvtToGeoJson.kt
app/src/main/java/org/scottishtecharmy/soundscape/geoengine/mvttranslation/WayGenerator.kt
app/src/main/java/org/scottishtecharmy/soundscape/geoengine/utils/TileUtils.kt
app/src/test/java/org/scottishtecharmy/soundscape/MvtTileTest.kt
app/src/test/java/org/scottishtecharmy/soundscape/TileUtilsTest.kt
app/src/test/res/org/scottishtecharmy/soundscape/travel-2.gpx

Add steps/tunnel/bridge to un-named way description even if it doesn't have a named endpoint.

Minor road name confection improvements

---

app/src/main/java/org/scottishtecharmy/soundscape/geoengine/utils/GpxRecorder.kt

Exporting only worked if the file already existed, which only happened when initially testing...oops.

Fix daft error exporting GPX files

---

app/src/androidTest/java/org/scottishtecharmy/soundscape/MvtPerformanceTest.kt
app/src/main/java/org/scottishtecharmy/soundscape/geoengine/GeoEngine.kt
app/src/main/java/org/scottishtecharmy/soundscape/geoengine/mvttranslation/WayGenerator.kt

Extend automated testing to cover the failing tile, and fix the underlying issue in FollowWays.

Fix crash in FollowWays #490

---

app/src/main/java/org/scottishtecharmy/soundscape/geoengine/filters/MapMatchFilter.kt
app/src/main/java/org/scottishtecharmy/soundscape/screens/onboarding/terms/TermsScreen.kt

The missing string was the "Scottish Tech Army Services Agreement"

Fix Terms of Service onboarding screen to not have stray %s

---

app/src/main/res/values-ja/strings.xml

Currently translated at 100.0% (449 of 449 strings)
Translation: Soundscape Android/Android app
Translate-URL: https://hosted.weblate.org/projects/soundscape-android/android-app/ja/

Translated using Weblate (Japanese)

---

app/src/main/java/org/scottishtecharmy/soundscape/screens/home/home/MapContainerLibre.kt
app/src/main/java/org/scottishtecharmy/soundscape/screens/home/locationDetails/SaveAndEditMarkerDialog.kt

In edit mode, the map can be scrolled to adjust the position of the marker.

Add location editing for Markers

---

app/src/main/java/org/scottishtecharmy/soundscape/audio/NativeAudioEngine.kt

Return an empty Set instead of a null.

Catch exception when TextToSpeech.voice is null
